env:
  TERM: "xterm"

steps:
  - command: "node --version"
  - command: "npm --version"
  - command: "npm install"
    label: "install dependencies"

  # delete any cached Cypress binary
  - "wait"
  - command: "$(npm bin)/cypress cache clear"

  - "wait"

  - command: "npm install $CYPRESS_NPM_PACKAGE_NAME"
    label: "install custom Cypress version"

  - "wait"

  - command: "$(npm bin)/cypress version"

  - "wait"

  - command: "npm run test:ci:record"
    label: "test"
